# Generated by Django 5.1.3 on 2024-12-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_friends_friend'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequests',
            unique_together={('created_by', 'created_for')},
        ),
    ]
