# Generated by Django 5.1.3 on 2024-11-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_attachments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postattachment',
            options={'ordering': ['-created_at']},
        ),
    ]
