# Generated by Django 5.1.3 on 2024-11-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options_alter_postattachment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='posts.postattachment'),
        ),
    ]
