# Generated by Django 5.1.7 on 2025-04-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(to='posts.postattachment'),
        ),
    ]
